version: '3.3'

services:

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379"
    volumes:
      - redis_data:/data

  nikita:
    container_name: nikita
    environment:
      twillio_sid: ${TWILLIO_SID}
      twillio_token: ${TWILLIO_TOKEN}
      twillio_phone: ${TWILLIO_PHONE}
      to_phone: ${TO_PHONE}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

volumes:
    redis_data:
