version: '3.3'

services:

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379"
    volumes:
      - redis_data:/data

  nikita:
    container_name: nikita
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

volumes:
    redis_data:
